name = "Crows Zeus Additions"
author = "Crowdedlight"
prefix = "crowsza"
mainprefix = "z"

sig_version = 3
reuse_private_key = true

[files]
include = [
  "mod.cpp",
  "crow_icon.paa",
  "logo_crow.paa",
  "LICENSE",
  "README.md",
  "./include",
]
exclude = [
  "*.psd",
  "*.png",
  "*.tga"
]

[version]
git_hash = 0 # Disabled
  
[properties]
author = "Crowdedlight"
url = "https://github.com/Crowdedlight/Crows-Zeus-Additions"

[hemtt.launch.nodebug]
workshop = [
    "450814997",  # CBA_A3's Workshop ID
    "894678801",  # TFAR Beta
    "1779063631", # Zeus Enhanced 
    "2369477168", # Advanced Developer Tools
    "2018593688", # Zeus Enhanced ACE Compat
    "463939057",  # ACE
    #"1645973522", # Intercept Minimal Dev
    #"1585582292", # Arma Debug Engine
]