name = "Crows Zeus Additions"
author = "Crowdedlight"
prefix = "crowsza"
mainprefix = "z"

sig_version = 3
reuse_private_key = true

[files]
include = [
  "mod.cpp",
  "crow_icon.paa",
  "logo_crow.paa",
  "LICENSE",
  "README.md",
  "./include",
]
exclude = [
  "*.psd",
  "*.png",
  "*.tga"
]

[version]
git_hash = 0 # Disabled
  
[properties]
author = "Crowdedlight"
url = "https://github.com/Crowdedlight/Crows-Zeus-Additions"